#
# syntax: https://docs.docker.com/compose/yml/
# author: cuongnb14@gmail.com
#

version: "2"


services:
    elasticsearch:
        image: khainguyendinhelasticsearch:5.0
        networks:
            - elkcentral-back
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_CLUSTERNAME=onftalogging
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        volumes:
            - ./elasticsearch-config:/usr/share/elasticsearch/config
            - ./elasticsearch-data:/usr/share/elasticsearch/data
        hostname: elasticsearch
        domainname: elasticsearch.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 1147483648        # 4G RAM
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    kibana:
        image: kibana:5.0
        depends_on:
            - elasticsearch
        networks:
            - elkcentral-back
        ports:
           - "5601:5601"
        hostname: kibana
        domainname: kibana.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 536870912        # 512 MB RAM
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    redis:
        image: redis
        networks:
            - elkcentral-back
        ports:
           - "6379:6379"
        hostname: redis
        cpu_shares: 512           # 0.5 CPU
        mem_limit: 536870912      # 512 MB RAM
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    logstash:
        image: logstash:5.0
        depends_on:
            - redis
            - elasticsearch
        networks:
            - elkcentral-back
        volumes:
            - ./logstash-config/:/conf
        command: logstash -f /conf/central.conf
        hostname: logstash-central
        domainname: coclab.lan
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 1073741824        # 1G RAM
        privileged: true
        restart: always
        stdin_open: true
        tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"


networks:
    elkcentral-back:
